#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class TextBox;
                ref class CheckBox;
                ref class Button;
                ref class ComboBox;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}

namespace SDKTemplate
{
    namespace WiFiTestTools
    {
        [::Windows::Foundation::Metadata::WebHostHidden]
        partial ref class WiFiClient : public ::Windows::UI::Xaml::Controls::Page, 
            public ::Windows::UI::Xaml::Markup::IComponentConnector,
            public ::Windows::UI::Xaml::Markup::IComponentConnector2
        {
        public:
            void InitializeComponent();
            virtual void Connect(int connectionId, ::Platform::Object^ target);
            virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
        
        private:
            bool _contentLoaded;
        
            private: ::Windows::UI::Xaml::Controls::TextBlock^ InputTextBlock0;
            private: ::Windows::UI::Xaml::Controls::TextBox^ HostNameForConnect;
            private: ::Windows::UI::Xaml::Controls::TextBox^ ServiceNameForConnect;
            private: ::Windows::UI::Xaml::Controls::TextBox^ TimeDuration;
            private: ::Windows::UI::Xaml::Controls::TextBox^ TimeInterval;
            private: ::Windows::UI::Xaml::Controls::TextBox^ ParallelNumber;
            private: ::Windows::UI::Xaml::Controls::TextBox^ SocketBufferSize;
            private: ::Windows::UI::Xaml::Controls::TextBox^ TcpMSS;
            private: ::Windows::UI::Xaml::Controls::CheckBox^ NoDelayMode;
            private: ::Windows::UI::Xaml::Controls::Button^ ClearReportMessages;
            private: ::Windows::UI::Xaml::Controls::TextBox^ ReportMessageBox;
            private: ::Windows::UI::Xaml::Controls::Button^ ConnectSocket;
            private: ::Windows::UI::Xaml::Controls::Button^ StopConnect;
            private: ::Windows::UI::Xaml::Controls::ComboBox^ TypeOfService;
            private: ::Windows::UI::Xaml::Controls::ComboBox^ cbIPv4v6;
            private: ::Windows::UI::Xaml::Controls::ComboBox^ cbTcpUdp;
            private: ::Windows::UI::Xaml::VisualState^ DefaultLayout;
            private: ::Windows::UI::Xaml::VisualState^ Below768Layout;
        };
    }
}

