//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "WiFiServer.xaml.h"

void ::SDKTemplate::WiFiTestTools::WiFiServer::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///WiFiServer.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::SDKTemplate::WiFiTestTools::WiFiServer::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->InputTextBlock1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 2:
            {
                this->ServerPortForListener = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 3:
            {
                this->TimeInterval = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 4:
            {
                this->ClearReportMessages = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ClearReportMessages))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKTemplate::WiFiTestTools::WiFiServer::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WiFiServer::ClearReportMessages_Click);
            }
            break;
        case 5:
            {
                this->ReportMessageBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 6:
            {
                this->StartListener = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->StartListener))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKTemplate::WiFiTestTools::WiFiServer::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WiFiServer::StartListener_Click);
            }
            break;
        case 7:
            {
                this->StopListener = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->StopListener))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKTemplate::WiFiTestTools::WiFiServer::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WiFiServer::StopListener_Click);
            }
            break;
        case 8:
            {
                this->DefaultLayout = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
            }
            break;
        case 9:
            {
                this->Below768Layout = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::SDKTemplate::WiFiTestTools::WiFiServer::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


